apiVersion: v1
kind: ConfigMap
metadata:
  name: report-service-config
  namespace: billme-platform
data:
  NODE_ENV: development
  PORT: "3013"
  POSTGRES_HOST: report-db-service
  POSTGRES_PORT: "5432"
  POSTGRES_USER: billme_report
  POSTGRES_DB: billme_reports
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: report-service-secrets
  namespace: billme-platform
type: Opaque
stringData:
  POSTGRES_PASSWORD: billme_report_pass
