apiVersion: v1
kind: Service
metadata:
  name: entity-service
  namespace: billme-platform
  labels:
    app: entity-service
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
  selector:
    app: entity-service
