apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: billme-platform
  labels:
    app: manager-service
spec:
  type: ClusterIP
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
  selector:
    app: manager-service
