apiVersion: v1
kind: Service
metadata:
  name: payment-db-service
  namespace: billme-platform
  labels:
    app: payment-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: payment-db
