apiVersion: v1
kind: Service
metadata:
  name: receipt-service
  namespace: billme-platform
  labels:
    app: receipt-service
spec:
  type: ClusterIP
  ports:
    - port: 3010
      targetPort: 3010
      protocol: TCP
  selector:
    app: receipt-service
