apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: billme-platform
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6370
      targetPort: 6370
      protocol: TCP
  selector:
    app: redis
