apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: billme-platform
  labels:
    app: report-service
spec:
  type: ClusterIP
  ports:
    - port: 3013
      targetPort: 3013
      protocol: TCP
  selector:
    app: report-service
